name: Build

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  HOME_DIR: ./package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Installing Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install
        working-directory: ${{env.HOME_DIR}}

      - name: Installing Dependencies
        run: yarn run start
        working-directory: ${{env.HOME_DIR}}

      - name: MS Notification
        uses: opsless/ms-teams-github-actions@main
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
